package servicelimiter

const (
	UNLIMITED_RATE = -1
	SECOND_PERIOD  = 1
	MINUTE_PERIOD  = 2
	HOUR_PERIOD    = 3
	DAY_PERIOD     = 4
	WEEK_PERIOD    = 5
	MONTH_PERIOD   = 6
	YEAR_PERIOD    = 7

	SECOND_TO_SECOND = 1
	MINUTE_TO_SECOND = 60
	HOUR_TO_SECOND   = MINUTE_TO_SECOND * 60
	DAY_TO_SECOND    = HOUR_TO_SECOND * 24
	WEEK_TO_SECOND   = DAY_TO_SECOND * 7
	MONTH_TO_SECOND  = DAY_TO_SECOND * 30
	YEAR_TO_SECOND   = DAY_TO_SECOND * 365
)

const (
	REDIS_BUCKET  = 0
	MEMORY_BUCKET = 1
)

const AUTO_SERVICE_NAME = "_"

const RATE_LIMIT_PREFIX = "rate_limiter_rl"
